# Generated by Django 6.0.3 on 2026-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('CENT', 'Cent')], default='PIECE', max_length=10),
        ),
    ]
