# Generated by Django 6.0.3 on 2026-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer')], default='STAFF', max_length=20),
        ),
    ]
