# Generated by Django 6.0.3 on 2026-03-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Product Code (leave blank to auto-generate)', max_length=50, null=True, unique=True),
        ),
    ]
